# Generated by Django 6.0.1 on 2026-01-30 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('wealth_impact', models.IntegerField(default=0)),
                ('happiness_impact', models.IntegerField(default=0)),
                ('credit_impact', models.IntegerField(default=0)),
                ('literacy_impact', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('NEEDS', 'Needs'), ('WANTS', 'Wants'), ('EMERGENCY', 'Emergency'), ('INVESTMENT', 'Investment'), ('SOCIAL', 'Social Pressure'), ('TRAP', 'Hidden Trap')], default='WANTS', max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
                ('min_month', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.IntegerField(default=1)),
                ('wealth', models.IntegerField(default=25000)),
                ('happiness', models.IntegerField(default=100)),
                ('credit_score', models.IntegerField(default=700)),
                ('financial_literacy', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.choice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_choices', to='game_engine.gamesession')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.scenariocard')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game_engine.scenariocard'),
        ),
    ]
