# Generated by Django 6.0.1 on 2026-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0006_alter_playerchoice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='market_trends',
            field=models.JSONField(default=dict),
        ),
    ]
