# Generated by Django 6.0.1 on 2026-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0008_add_profile_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='purchase_history',
            field=models.JSONField(default=list),
        ),
    ]
