# Generated by Django 6.0.1 on 2026-02-09 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0012_choice_feedback_hi_choice_feedback_mr_choice_text_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='final_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='gameplay_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='gold_holdings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='real_estate_holdings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('RENTAL', 'Rental'), ('DIVIDEND', 'Dividend'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20)),
                ('amount_base', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('variability', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('ONE_TIME', 'One-time')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='game_engine.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_stage', models.CharField(choices=[('STUDENT_FULLY_FUNDED', 'Student (Fully Funded)'), ('STUDENT_PART_TIME', 'Student (Part Time)'), ('FRESHER', 'Fresher'), ('PROFESSIONAL', 'Professional'), ('BUSINESS_OWNER', 'Business Owner'), ('RETIRED', 'Retired')], default='FRESHER', max_length=20)),
                ('responsibility_level', models.CharField(choices=[('LOW', 'Low (No dependents)'), ('MEDIUM', 'Medium (Rent/EMIs)'), ('HIGH', 'High (Family support)')], default='MEDIUM', max_length=50)),
                ('risk_appetite', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_profile', to='game_engine.gamesession')),
            ],
        ),
    ]
