# Generated by Django 6.0.1 on 2026-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0013_gamesession_current_level_gamesession_final_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocard',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
