# Generated by Django 6.0.1 on 2026-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0014_scenariocard_is_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='active_ipos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='mutual_funds',
            field=models.JSONField(default=dict),
        ),
    ]
