# Generated by Django 6.0.1 on 2026-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0016_markettickerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='monthly_salary',
            field=models.IntegerField(default=25000),
        ),
    ]
