# Generated by Django 6.0.1 on 2026-02-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0017_gamesession_monthly_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('units', models.FloatField(default=0.0)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('month', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game_engine.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('units', models.FloatField(default=0.0)),
                ('average_buy_price', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='game_engine.gamesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'sector'], name='game_engine_session_6f187a_idx')],
                'unique_together': {('session', 'sector')},
            },
        ),
    ]
