# Generated by Django 6.0.1 on 2026-02-15 18:55

from django.db import migrations



def migrate_data(apps, schema_editor):
    GameSession = apps.get_model('game_engine', 'GameSession')
    PortfolioItem = apps.get_model('game_engine', 'PortfolioItem')
    TransactionLedger = apps.get_model('game_engine', 'TransactionLedger')

    for session in GameSession.objects.all():
        # 1. Migrate Portfolio
        if session.portfolio:
            for sector, units in session.portfolio.items():
                if units > 0:
                    PortfolioItem.objects.create(
                        session=session,
                        sector=sector,
                        units=float(units),
                        average_buy_price=0.0 # Unknown, defaulting to 0
                    )

        # 2. Migrate Purchase History
        if session.purchase_history:
            for record in session.purchase_history:
                # record format: {"sector": "tech", "units": 10, "price": 100, "month": 1}
                TransactionLedger.objects.create(
                    session=session,
                    transaction_type='BUY', # Old history only tracked buys
                    sector=record.get('sector', 'unknown'),
                    units=float(record.get('units', 0)),
                    price_per_unit=float(record.get('price', 0)),
                    total_amount=float(record.get('units', 0)) * float(record.get('price', 0)),
                    month=record.get('month', session.current_month),
                    timestamp=session.created_at # Approximate timestamp
                )

class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0018_transactionledger_portfolioitem'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
